---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: polaris
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: gp2