# LIVE DEBUGGING OF THE ATTACHED PVC
apiVersion: v1
kind: Pod
metadata:
  name: pvc-test
spec:
  containers:
  - name: busybox
    image: docker.io/maven:3.6.3-jdk-8
    command:
      - tail
    args:
      - -f 
      - /dev/null
    volumeMounts:
          - name: seeker
            mountPath: /seeker
    resources:
          requests:
            memory: "218Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "200m"
  volumes:
  - name: seeker
    persistentVolumeClaim:
      claimName: seeker-pvc # create a pvc named polaris
