---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seeker-pvc
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: gp2